scenario1:
  IP_CIDR1 : '172.32.1.0/24'
  IP_CIDR2 : '172.32.0.0/24'
  VPC1 : 'custom_vpc_1'
  VPC2 : 'custom_vpc_2'
  SUBNET_CIDR11 : '172.32.1.0/25'
  SUBNET_CIDR12 : '172.32.1.128/25'
  SUBNET_CIDR21 : '172.32.0.0/25'
  SUBNET1_VPC1 : 'public_subnet_vpc1'
  SUBNET2_VPC1 : 'private_subnet_vpc1'
  SUBNET1_VPC2 : 'private_subnet_vpc2'
  IGW : 'igw'
  VPC1_PUB_ROUTE_TABLE : 'vpc1_pub_route_table'
  VPC2_PRI_ROUTE_TABLE : 'vpc2_pri_route_table'
  VPC1_PRI_ROUTE_TABLE : 'vpc1_pri_route_table'
  TGW : 'tgw'
  TGW_ATTACH_VPC1 : 'tgw_attach_vpc1'
  TGW_ATTACH_VPC2 : 'tgw_attach_vpc2'
  EC2_PUB_1_VPC1 : 'instance_public_vpc1'
  EC2_PRI_2_VPC1 : 'instance_private_vpc1'
  EC2_PRI_1_VPC2 : 'instance_private_vpc2'
  SG_PUB_1_VPC1 : 'sg_pub_vpc1'
  SG_PRI_2_VPC1 : 'sg_pri_vpc1'
  SG_PRI_1_VPC2 : 'sg_pri_vpc2'