intra_region:
  IP_CIDR1 : '172.32.1.0/24'
  IP_CIDR2 : '172.32.0.0/24'
  VPC1 : 'custom_vpc_1'
  VPC2 : 'custom_vpc_2'
  SUBNET_CIDR11 : '172.32.1.0/25'
  SUBNET_CIDR12 : '172.32.1.128/25'
  SUBNET_CIDR21 : '172.32.0.0/25'
  SUBNET1_VPC1 : 'public_subnet_vpc1'
  SUBNET2_VPC1 : 'private_subnet_vpc1'
  SUBNET1_VPC2 : 'private_subnet_vpc2'
  IGW : 'igw'
  VPC1_PUB_ROUTE_TABLE : 'vpc1_pub_route_table'
  VPC2_PRI_ROUTE_TABLE : 'vpc2_pri_route_table'
  VPC1_PRI_ROUTE_TABLE : 'vpc1_pri_route_table'
  TGW : 'tgw'
  TGW_ATTACH_VPC1 : 'tgw_attach_vpc1'
  TGW_ATTACH_VPC2 : 'tgw_attach_vpc2'
  EC2_PUB_1_VPC1 : 'instance_public_vpc1'
  EC2_PRI_2_VPC1 : 'instance_private_vpc1'
  EC2_PRI_1_VPC2 : 'instance_private_vpc2'
  SG_PUB_1_VPC1 : 'sg_pub_vpc1'
  SG_PRI_2_VPC1 : 'sg_pri_vpc1'
  SG_PRI_1_VPC2 : 'sg_pri_vpc2'
inter_region:
  IP_CIDR1: '172.32.2.0/24'
  IP_CIDR2: '172.32.3.0/24'
  VPC1: 'us_east_1_vpc'
  VPC2: 'us_west_1_vpc'
  REGION1: 'us-east-1'
  REGION2: 'us-west-1'
  REGION1_AZ: 'us-east-1d'
  REGION2_AZ: 'us-west-1a'
  SUBNET_CIDR11: '172.32.2.0/25'
  SUBNET_CIDR12: '172.32.2.128/25'
  SUBNET_CIDR21: '172.32.3.0/25'
  SUBNET1_VPC1: 'us_east_1d_public_subnet_vpc1'
  SUBNET2_VPC1: 'us_east_1d_private_subnet_vpc1'
  SUBNET1_VPC2: 'us_west_1a_private_subnet_vpc2'
  IGW: 'igw'
  VPC1_PUB_ROUTE_TABLE: 'us_east_1_public_rt_vpc1'
  VPC1_PRI_ROUTE_TABLE: 'us_east_1_private_rt_vpc1'
  VPC2_PRI_ROUTE_TABLE: 'us_west_1_private_rt_vpc2'
  TGW_1 : 'us_east_1_tgw_1'
  TGW_2 : 'us_west_1_tgw_2'
  TGW_PEER_CONNECT : 'tgw_peer_connection'
  TGW_ATTACH_VPC1: 'us_east_1_tgw_attach_vpc1'
  TGW_ATTACH_VPC2: 'us_west_1_tgw_attach_vpc2'
  TGW_1_ROUTE_TABLE: 'us_east_1_tgw_1_route_table'
  TGW_2_ROUTE_TABLE: 'us_west_1_tgw_2_route_table'
  US_EAST_1_IMAGE: 'ami-065bb5126e4504910'
  US_WEST_1_IMAGE: 'ami-00569e54da628d17c'
  EC2_PUB_1_VPC1: 'us_east_1_instance_public_vpc1'
  EC2_PRI_2_VPC1: 'us_east_1_instance_private_vpc1'
  EC2_PRI_1_VPC2: 'us_west_1_instance_private_vpc2'
  SG_PUB_1_VPC1: 'us_east_1_sg_pub_vpc1'
  SG_PRI_2_VPC1: 'us_east_1_sg_pri_vpc1'
  SG_PRI_1_VPC2: 'us_west_1_sg_pri_vpc2'